Character view
Icyr/DnDApp pull request #18
Opened 2020-03-18 09:49 UTC by dndappb412d

#6

2020-03-18 17:50 UTC, Icyr requested changes

2020-03-18 17:50 UTC, Icyr commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0'
Нужно убрать

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/values/strings.xml
> +    <string name="dnd_logo" />
Это нужно удалить

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/values/strings.xml
>      <string name="sign_up_submit">Sign Up</string>
Сделай для строк префикс экрана, как выше.
Т.е character_view_name

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_margin">16dp</dimen>
Добавь префикс названия фрагмента.
character_view_name_margin

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/layout/fragment_character_entity.xml
> +        android:contentDescription="@string/dnd_logo" />
В этом нет смысла, на contentDescription можно забить.

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/layout/fragment_character_entity.xml
> +        android:text="@string/character_name_text_view"
В этом нет смысла, удали.

2020-03-18 17:50 UTC, Icyr commented on app/src/main/java/com/dndapp/character/list/CharacterListAdapter.kt
> +) : GenericAdapter<String, Character, CharacterViewHolder>(), KoinComponent, CharacterListItemClickHandler {
- Скобки можно убрать
- Если интерфейсы слишком длинные, расположим их по 1 на строке

2020-03-18 17:50 UTC, Icyr commented on app/src/main/java/com/dndapp/character/entity/CharacterEntityFragment.kt
> +class CharacterEntityFragment : Fragment() {
- Убрать лишнюю строку перед фрагментом
- Странное название, почему не CharacterView?

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/layout/fragment_character_entity.xml
> +        android:layout_marginEnd="60dp"
Захардкоженные значения следует вынести в dimens.xml

2020-03-18 17:50 UTC, Icyr commented on app/src/main/res/layout/fragment_character_entity.xml
> +        android:layout_marginStart="36dp"
Захардкоженные значения следует вынести в dimens.xml

2020-03-18 19:01 UTC, dndappb412d commented on app/src/main/res/layout/fragment_character_entity.xml
> +        android:text="@string/character_name_text_view"
удалил   android:text="@string/character_name_text_view" 
при удалении остальных строк ругается на тэг TextView
![image](https://user-images.githubusercontent.com/62158267/76997219-6334a380-696c-11ea-9c23-02a0933a58cc.png)

2020-03-19 06:18 UTC, Icyr approved these changes

2020-03-19 06:18 UTC, merged